language: cpp
compiler:
  - gcc
env:
  - NGINX_VERSION="1.7.4"
before_install:
  - sudo apt-get install -y gcc build-essential libsndfile1-dev libasound2-dev libjack-dev libqt4-dev
install:
  - curl -LO http://nginx.org/download/nginx-${NGINX_VERSION}.tar.gz
  - tar xvzf nginx-${NGINX_VERSION}.tar.gz
  - cd nginx-${NGINX_VERSION}/
script:
  - ./configure --prefix=/usr/local/nginx --sbin-path=/usr/local/sbin/nginx --conf-path=/etc/nginx/nginx.conf --error-log-path=/var/log/nginx/error.log --http-log-path=/var/log/nginx/access.log --pid-path=/run/nginx.pid --lock-path=/run/lock/subsys/nginx --user=nginx --group=nginx --with-file-aio --with-ipv6 --with-http_ssl_module --with-http_spdy_module --with-http_realip_module --with-http_addition_module --with-http_xslt_module --with-http_image_filter_module --with-http_geoip_module --with-http_sub_module --with-http_dav_module --with-http_flv_module --with-http_mp4_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_random_index_module --with-http_secure_link_module --with-http_degradation_module --with-http_stub_status_module --with-http_perl_module --with-mail --with-mail_ssl_module --with-pcre --with-google_perftools_module --with-debug  
  - make 
#  - make install
# deploy:
#   provider: releases
#   api-key: "GITHUB OAUTH TOKEN"
#   file: "FILE TO UPLOAD"
#   skip_cleanup: true
#   on:
#     tags: true
#     all_branches: true
