language: cpp
compiler:
  - gcc
env:
  - NGINX_VERSION="1.7.4"
before_install:
  - sudo apt-get install -y gcc build-essential libsndfile1-dev libasound2-dev libjack-dev libqt4-dev
install:
  - curl -LO http://nginx.org/download/nginx-${NGINX_VERSION}.tar.gz
  - tar xvzf nginx-${NGINX_VERSION}.tar.gz
  - cd nginx-${NGINX_VERSION}/
script:
  - cmake
  - make 
#  - make install
# deploy:
#   provider: releases
#   api-key: "GITHUB OAUTH TOKEN"
#   file: "FILE TO UPLOAD"
#   skip_cleanup: true
#   on:
#     tags: true
#     all_branches: true
